services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=dashboard'
      - 'MYSQL_PASSWORD=a'
      - 'MYSQL_ROOT_PASSWORD=a'
      - 'MYSQL_USER=root'
    ports:
      - '3306'
